apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: laravel-mutex-migrations
  annotations:
    github.com/project-slug: yourparkingspace/laravel-mutex-migrations
spec:
  type: service
  lifecycle: production
  owner: marketplace-backend
